/* This file is automatically generated by NRPy+. Do not edit. */

/* EVOLVED VARIABLES: */
#define NUM_EVOL_GFS 26
#define PHIGF	0
#define PIGF	1
#define ADD00GF	2
#define ADD01GF	3
#define ADD02GF	4
#define ADD11GF	5
#define ADD12GF	6
#define ADD22GF	7
#define ALPHAGF	8
#define BETU0GF	9
#define BETU1GF	10
#define BETU2GF	11
#define CFGF	12
#define HDD00GF	13
#define HDD01GF	14
#define HDD02GF	15
#define HDD11GF	16
#define HDD12GF	17
#define HDD22GF	18
#define LAMBDAU0GF	19
#define LAMBDAU1GF	20
#define LAMBDAU2GF	21
#define TRKGF	22
#define VETU0GF	23
#define VETU1GF	24
#define VETU2GF	25


 /* AUXILIARY VARIABLES: */
#define NUM_AUX_GFS 1
#define HGF	0


 /* AUXEVOL VARIABLES: */
#define NUM_AUXEVOL_GFS 6
#define RBARDD00GF	0
#define RBARDD01GF	1
#define RBARDD02GF	2
#define RBARDD11GF	3
#define RBARDD12GF	4
#define RBARDD22GF	5


/* PARITY TYPES FOR ALL GRIDFUNCTIONS.
   SEE "Tutorial-Start_to_Finish-Curvilinear_BCs.ipynb" FOR DEFINITIONS. */
const int8_t evol_gf_parity[26] = { 0, 0, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 0, 4, 5, 6, 7, 8, 9, 1, 2, 3, 0, 1, 2, 3 };
const int8_t aux_gf_parity[1] = { 0 };
const int8_t auxevol_gf_parity[6] = { 4, 5, 6, 7, 8, 9 };
