/* This file is automatically generated by NRPy+. Do not edit. */

/* EVOLVED VARIABLES: */
#define NUM_EVOL_GFS 2
#define PHIGF	0
#define PIGF	1


 /* AUXILIARY VARIABLES: */
#define NUM_AUX_GFS 0


 /* AUXEVOL VARIABLES: */
#define NUM_AUXEVOL_GFS 0


/* PARITY TYPES FOR ALL GRIDFUNCTIONS.
   SEE "Tutorial-Start_to_Finish-Curvilinear_BCs.ipynb" FOR DEFINITIONS. */
const int8_t evol_gf_parity[2] = { 0, 0 };
